export const READ_ITEM = 'item/read_item'
export const CREATE_ITEM = 'item/create_item'
export const UPDATE_ITEM = 'item/update_item'
export const REMOVE_ITEM = 'item/remove_item'
export const RESEND_ITEM = 'item/resend_item'

export const READ_CART = 'cart/read_cart'
export const CREATE_CART = 'cart/create_cart'
export const UPDATE_CART = 'cart/update_cart'
export const REMOVE_CART = 'cart/remove_cart'
export const RESEND_CART = 'cart/resend_cart'